# Generated by Django 3.2.6 on 2021-08-02 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPool',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_to', models.BooleanField(default=False)),
                ('expiry_time', models.DateTimeField(null=True)),
                ('refresh_time', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Token Pool Collection',
                'verbose_name_plural': 'Token Pool Collections',
                'db_table': 'token_pool_collection',
            },
        ),
    ]
